# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20171005_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='quizz',
        ),
        migrations.AddField(
            model_name='quizz',
            name='hash',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='hash',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'static/upload/'),
        ),
    ]
