# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20171006_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/upload/'),
        ),
    ]
