# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_auto_20171006_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='idUser',
        ),
        migrations.AddField(
            model_name='score',
            name='quizz',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quizz.Quizz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretoquestion',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.Score'),
        ),
    ]
