# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_auto_20171007_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='point',
            field=models.IntegerField(default=-1),
        ),
    ]
